---
- name: Installer Apache, PHP et WordPress sur le serveur middle
  hosts: middle_dev
  become: true

  vars:
    db_host: 192.168.50.151  # Adresse de la machine back
    db_name: wordpress
    db_user: wp_user
    db_password: wp_pass
    wordpress_dir: /var/www/html

  tasks:
    - name: Installer Apache, PHP et extensions nécessaires
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Télécharger WordPress
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip

    - name: Décompresser WordPress
      unarchive:
        src: /tmp/wordpress.zip 
        dest: "{{ wordpress_dir }}"
        remote_src: yes 
        owner: www-data
        group: www-data 
        mode: '0755'



    - name: Créer le fichier wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: "{{ wordpress_dir }}/wordpress/wp-config.php"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Assurer que les permissions sont correctes sur le dossier WordPress
      file:
        path: "{{ wordpress_dir }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Démarrer Apache et l'activer au démarrage
      service:
        name: apache2
        state: started
        enabled: true
