- name: Installer Wordpress
  hosts: middle_dev
  become: true

- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Copier le fichier wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: S'assurer des bons droits
  file:
    path: /var/www/html/wordpress
    recurse: yes
    owner: www-data
    group: www-data
